# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
os:
  - linux
  - osx
language: R
sudo: required
cache: packages
r:
  - oldrel
  - release
  - devel
matrix:
  exclude:
    - os: osx
      r: devel
  include:
  - r: oldrel
    before_cache:
    - Rscript -e 'install_version("mvtnorm", version = "1.0-8", repos = "http://cran.us.r-project.org")'

